spring:
  application:
    name: hackathon_tusur
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: zdraviymalish@gmail.com
    password: nfjz gwye cyxb yplw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

amazonProperties:
  endpointUrl: https://storage.yandexcloud.net
  bucketName: hackathon-tinkoff-birthdate-bucket

yandexApi:
  foundationModelsUri: https://llm.api.cloud.yandex.net/foundationModels/v1/completion
  token: AQVN328SgQPANy5vY4xIWhPuzKoYYzqjOld6KB6j
  modelUri: gpt://b1go9ij03gceo2iisf9b/yandexgpt

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
