spring:
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/hackathon
    username: postgres
    password: cNBxF5Ang977BPz7kUr2jHHBMu6bQfnh
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: postgres

authServer:
  authorizationUrl: http://localhost:8082/realms/hits-project/protocol/openid-connect/auth
  tokenUrl: http://localhost:8082/realms/hits-project/protocol/openid-connect/token
  refreshUrl: http://localhost:8082/realms/hits-project/protocol/openid-connect/token

server:
  port: 8080