spring:
  liquibase:
    enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jooq:
    sql-dialect: postgres

authServer:
  authorizationUrl: http://51.250.30.109:8082/realms/hits-project/protocol/openid-connect/auth
  tokenUrl: http://51.250.30.109:8082/realms/hits-project/protocol/openid-connect/token
  refreshUrl: http://51.250.30.109:8082/realms/hits-project/protocol/openid-connect/token

server:
  port: 8080